#!/bin/sh

if [ -z "$CHROMIX" ]
then
   cat <<EOF
Error: \$CHROMIX is not set.

Set the CHROMIX environment variable to the path of the chromix Javascript file.
For example, put something like the following in your startup scripts:

export CHROMIX=\$HOME/local/project/chromix/script/chromix.js
EOF
   exit 1
fi >&2

if ! [ -r "$CHROMIX" ]
then
   cat <<EOF
Error: \$CHROMIX does not exist or is not readable: $CHROMIX
EOF
   exit 1
fi >&2

exec node "$CHROMIX" "$@"

